# Generated by Django 6.0.7 on 2026-07-21 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kingdom', models.CharField(max_length=100)),
                ('max_capacity', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('MAGE', 'Mago'), ('WARRIOR', 'Guerrero'), ('ROGE', 'Picaro'), ('Cleric', 'Clerigo')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Mago'), ('MISSION', 'En Mision'), ('DEAD', 'Muerto en combate')], default='ACTIVE', max_length=20)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventurers', to='api.guild')),
            ],
        ),
    ]
