FROM python:3.12-slim

#Evita guardar archivos .pyc en docker
ENV PYTHONDONTWRITEBYTECODE 1

#Evita que python retrase los pips en la consola
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/